### ISSUE TITLE
Pledge button should open Facebook sharing Window

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/swear-jar#17]
Same window as user sees when they click the "Share" button

**Comment by jjandoc** [comment]
So what's the exact UX flow for this? I enter my email, click "pledge", and then an FB dialog box shows up? That seems odd and jarring to be taken from one website to another. I kind of feel like we need some kind of confirmation messaging beyond "Thanks" that has a CTA to share rather than forcing the FB share dialog.

Also, from a technical perspective most browser pop-up blockers will prevent the FB share window from opening after the AJAX callback. Generally that sort of thing needs to happen in immediate response to a user input.

**Comment by AaronSofaer** [comment]
Agreed; when a user pledges we should open a modal confirmation box with a CTA to share.

**Comment by jjandoc** [comment]
Fixed in #29
