### ISSUE TITLE
Add GA tracking

### ISSUE THREAD

**Issue by jmithani** [DevProgress/swear-jar#32]
Implement Google Analytics tracking for the page. Should we track shares and signup button clicks, or will that be an unuseful duplicate of information we already will have collected?

**Comment by AaronSofaer** [comment]
I think tracking all of the analytics in the same place (eg, GA) is a good idea just so we aren't syncretising data from multiple locations.

**Comment by decause** [comment]
I thought I'd sent this, but if you don't have the code, ping me and I'll
generate one.
On Oct 9, 2016 11:18 AM, "Aaron Sofaer" notifications@github.com wrote:

I think tracking all of the analytics in the same place (eg, GA) is a good
idea just so we aren't syncretising data from multiple locations.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/DevProgress/swear-jar/issues/32#issuecomment-252502767,
or mute the thread

**Comment by jmithani** [comment]
I won't be able to do this until earliest 7pm CDT because of school, if we want it earlier pre-debate someone else should take this on.

**Comment by AaronSofaer** [comment]
We don't need this for the launch MVP.

**Comment by jmithani** [comment]
Okay, then I got it and will do it tonight!

**Comment by decause** [comment]
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83595614-9', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by AaronSofaer** [comment]
Fixed by @ldworkin , thank you!
